"""add created_at to vacancies

Revision ID: 8125bf2f887b
Revises: 22ba62d6abfe
Create Date: 2025-03-07 16:56:26.513575

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8125bf2f887b"
down_revision: Union[str, None] = "22ba62d6abfe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vacancies", sa.Column("created_at", sa.Date(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vacancies", "created_at")
    # ### end Alembic commands ###
